# Generated by Django 4.2.6 on 2023-12-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_key',
            field=models.IntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
