# Generated by Django 4.2.6 on 2023-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_user_personal_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_key',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
