# Generated by Django 4.2.6 on 2023-12-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_alter_user_personal_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal_key',
        ),
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Personal ID'),
        ),
    ]
