# Generated by Django 4.2.6 on 2023-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_remove_user_personal_key_user_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='personal_id'),
        ),
    ]
