# Generated by Django 4.2.6 on 2023-12-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_user_personal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='personal_id',
            new_name='personal_key',
        ),
    ]
