# Generated by Django 4.2.6 on 2023-12-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='design_hr_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='recording_hr_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
